### ISSUE TITLE
Crash can occur when attempting to validate gene, causes application crash

### ISSUE THREAD

**Issue by jcdesimp** [tair/toastdos-back#155]
```
GET /api/submission/list 200 49.820 ms - 2
OPTIONS /api/gene/verify/AT2G20120 200 12.954 ms - 8
GET /api/gene/verify/AT2G20120 200 3637.177 ms - 94
OPTIONS /api/gene/verify/D7L5B6 200 0.512 ms - 8
/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/lib/uniprot_api.js:34
					let taxonName = body[0].organism.match(TAXON_EXTRACTING_REGEX)[1];
					                                                              ^

TypeError: Cannot read property '1' of null
    at Request.request.get [as _callback] (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/lib/uniprot_api.js:34:68)
    at Request.self.callback (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Mimickal** [comment]
A GET on this endpoint [http://www.uniprot.org/uniprot/?format=json&limit=2&query=accession:D7L5B6](http://www.uniprot.org/uniprot/?format=json&limit=2&query=accession:D7L5B6) returns:
```
[
  {
    "id": "D7L5B6",
    "entry name": "D7L5B6_ARALL",
    "reviewed": "unreviewed",
    "protein names": "Putative uncharacterized protein",
    "genes": "ARALYDRAFT_480456",
    "organism": "Arabidopsis lyrata subsp. lyrata (Lyre-leaved rock-cress)",
    "length": "266"
  }
]
```

We attempt to match `body[0].organism` using the regex `/^(\b[\w ]+\b) *(?:\(.*)?$/`. We want this to extract "Arabidopsis lyrata", but the regex doesn't actually match because of the "." in "subsp. lyrata".

The NCBI Taxonomy database will actually give us a result for "Arabidopsis lyrata subsp. lyrata". We just need to improve the regex to match that string.
