### ISSUE TITLE
Bug with getting a single submission

### ISSUE THREAD

**Issue by jcdesimp** [tair/toastdos-back#176]
```11:23:25 AM - error:  TypeError: Cannot read property 'related' of null
    at Submission.where.fetch.then.then.submission (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/controllers/submission.js:344:43)
From previous event:
    at getSingleSubmission (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/controllers/submission.js:341:4)
    at Layer.handle [as handle_request] (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/express/lib/router/route.js:131:13)
    at requireCurator (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/middleware/authentication.js:76:3)
    at Layer.handle [as handle_request] (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/express/lib/router/route.js:131:13)
    at User.where.fetch.then.user (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/middleware/authentication.js:48:5)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at auth.verifyToken (/Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/app/middleware/authentication.js:46:5)
    at /Users/jcdesimp/Documents/Projects/seniorProj/toastdos-back/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Mimickal** [comment]
This workflow works in SQLite3, but breaks in PostgreSQL. This appears to be an issue with some interaction between Bookshelf's `withRelated` functionality and the PostgreSQL driver. Calling `.fetch({withRelated: ...})` on a model after the initial fetch returns null.

One potential workaround we've found is to do all of the `withRelated` stuff in the initial fetch. This would require a lot of code duplication for each Annotation format, but would probably work.

Additionally, a bug report should be put in for Bookshelf, as this seems to be a problem on their end.
